// export const DEFALUT_URL = 'http://10.11.11.1:8000';
export const DEFALUT_URL = 'http://wtr.oulhafiane.me'
export const DEFALUT_URL_HUB = 'http://wtr.oulhafiane.me:3000';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';
export const ROLE_PICKER = 'ROLE_PICKER';
export const ROLE_RESELLER = 'ROLE_RESELLER';
export const ROLE_BUYER = 'ROLE_BUYER';

// Category consts

export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_FAIL = 'FETCH_CATEGORIES_FAIL';


// Post an Offer

export const SALE_SUCCESS = 'SALE_SUCCESS';
export const SALE_FAILURE = 'SALE_FAILURE';

// Fetch offers

export const FETCH_SALES_SUCCESS = 'FETCH_SALES_SUCCESS';
export const FETCH_SALES_FAILURE = 'FETCH_SALES_FAILURE';

// FETCH OFFER BY ID

export const FETCH_OFFER_SUCCESS = 'FETCH_OFFER_SUCCESS';
export const FETCH_OFFER_FAILURE = 'FETCH_OFFER_FAILURE';

// IMAGE SIZE

export const IMGE_SIZE = 6;

// FETCH CURRENT USER INFO

export const FETCH_USER_INFO_SUCCESS = 'FETCH_USER_INFO_SUCCESS';
export const FETCH_USER_INFO_FAILURE = 'FETCH_USER_INFO_FAILURE';

// FETCH CURRENT USER NOTIFICATION

export const FETCH_NOTIFICATION_SUCCESS = 'FETCH_NOTIFICATION_SUCCESS';
export const FETCH_NOTIFICATION_FAILURE = 'FETCH_NOTIFICATION_FAILURE';


// FETCH CURRENT USER MESSAGES

export const FETCH_MESSAGES_SUCCESS = 'FETCH_MESSAGES_SUCCESS';
export const FETCH_MESSAGES_FAILURE = 'FETCH_MESSAGES_FAILURE';

// EDIT CURRENT USER MESSAGE
export const EDIT_MESSAGES_SUCCESS = 'EDIT_MESSAGES_SUCCESS';

// EDIT CURRENT USER NOTIFICATION
export const EDIT_NOTIFICATION_SUCCESS = 'EDIT_NOTIFICATION_SUCCESS';

// Mercure notification const
export const MERCURE_NOTIFICATION_UPDATE = 'MERCURE_NOTIFICATION_UPDATE';

// FETCH USER INFO

export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE';

// Terminate transaction
export const TERMINATE_TRANS_SUCCESS = 'TERMINATE_TRANS_SUCCESS';
export const TERMINATE_TRANS_FAILURE = 'TERMINATE_TRANS_FAILURE';

//Fetch current user offers
export const FETCH_CURRENT_USER_OFFER = 'FETCH_CURRENT_USER_OFFER';
export const FETCH_CURRENT_USER_AUCTIONS = 'FETCH_CURRENT_USER_AUCTIONS';

// Sending / fetching message to / with a user
export const MESSAGE_SENT_SUCCESS = 'MESSAGE_SENT_SUCCESS';
export const MESSAGE_SENT_FAILURE = 'MESSAGE_SENT_FAILURE';
export const MESSAGES_FETCH_SUCCESS = 'MESSAGES_FETCH_SUCCESS';

// CONST OF THE MERCURE MESSAGE
export const MERCURE_MESSAGE_UPDATE = 'MERCURE_MESSAGE_UPDATE';