// export const DEFALUT_URL = 'http://10.11.11.1:8000';
export const DEFALUT_URL = 'http://wtr.oulhafiane.me'
export const DEFALUT_URL_HUB = 'http://wtr.oulhafiane.me:3000';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';

// Category consts

export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_FAIL = 'FETCH_CATEGORIES_FAIL';


// Post an Offer

export const SALE_SUCCESS = 'SALE_SUCCESS';
export const SALE_FAILURE = 'SALE_FAILURE';

// Fetch offers

export const FETCH_SALES_SUCCESS = 'FETCH_SALES_SUCCESS';
export const FETCH_SALES_FAILURE = 'FETCH_SALES_FAILURE';

// FETCH OFFER BY ID

export const FETCH_OFFER_SUCCESS = 'FETCH_OFFER_SUCCESS';
export const FETCH_OFFER_FAILURE = 'FETCH_OFFER_FAILURE';

// IMAGE SIZE

export const IMGE_SIZE = 6;

// FETCH CURRENT USER INFO

export const FETCH_USER_INFO_SUCCESS = 'FETCH_USER_INFO_SUCCESS';
export const FETCH_USER_INFO_FAILURE = 'FETCH_USER_INFO_FAILURE';

// FETCH CURRENT USER NOTIFICATION

export const FETCH_NOTIFICATION_SUCCESS = 'FETCH_NOTIFICATION_SUCCESS';
export const FETCH_NOTIFICATION_FAILURE = 'FETCH_NOTIFICATION_FAILURE';


// FETCH CURRENT USER MESSAGES

export const FETCH_MESSAGES_SUCCESS = 'FETCH_MESSAGES_SUCCESS';
export const FETCH_MESSAGES_FAILURE = 'FETCH_MESSAGES_FAILURE';